title: AI Incident Forecasting Blog
description: Results & updates from the AI‑incident forecasting project
theme: minima
author:
  - Ahmed Elbashir
  - Chamod Kalupahana
  - Christopher L. Lübbers
description: >
  This site documents the **AI Incident Forecasting** project developed during the Apart AI Forecasting Hackathon.
  