title: AI Incident Forecasting Blog
description: Results & updates from the AI‑incident forecasting project
theme: minima
authors:
  - name: "Ahmed Elbashir"
  - name: "Chamod Kalupahana"
  - name: "Christopher L. Lübbers"